language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew upgrade xctool
  - gem install cocoapods -v '0.33.1'
script:
  - xctool -workspace DTStorage.xcworkspace -scheme DTStorage -sdk iphonesimulator build test
